---
title: "Gene expression along trajectory"
author: "Koen Van den Berge"
date: "3/11/2021"
output: html_document
---

```{r pkg}
here::set_here()
suppressPackageStartupMessages({
  library(slingshot)
  library(tradeSeq)
  library(SingleCellExperiment)
  library(cowplot)
  library(rgl)
  library(clusterExperiment)
  library(RColorBrewer)
  library(aggregation)
  library(ggplot2)
  library(pheatmap)
  library(wesanderson)
  library(UpSetR)
  library(gridExtra)
})
colby <- function(values, g=4){
  if(is(values, "character")){
    cols <- as.numeric(as.factor(values))
    return(cols)
  }
  if(is(values, "factor")){
    ncl <- nlevels(values)
    if(ncl > 9){
          colpal <- c(RColorBrewer::brewer.pal(9, 'Set1'), wesanderson::wes_palette("Darjeeling1", n=ncl-9, type="continuous"))
    } else {
       colpal <- RColorBrewer::brewer.pal(9, 'Set1')
    }
    cols <- colpal[as.numeric(values)]
    return(cols)
  }
  if(is(values, "numeric")){
    pal <- wesanderson::wes_palette("Zissou1", n=g, type="continuous")
    gg <- Hmisc::cut2(values, g=g)
    if(nlevels(gg) < g){
      nl <- nlevels(gg)
      if(nl == 2) pal <- pal[c(1,g)]
    }
    cols <- pal[gg]
    return(cols)
  }
}
```

# Import data

```{r loadData}
sds <- readRDS("../data/finalTrajectory/sling.rds")
counts <- readRDS("../data/finalTrajectory/counts_noResp_noMV.rds")
counts <- round(counts)
sce <- readRDS("../data/finalTrajectory/sce_tradeSeq20200904.rds")
load("../data/ALL_TF.Rda")
clDatta <- readRDS("../data/finalTrajectory/dattaCl_noResp_noMV.rds")
```

# Trajectory

```{r}
plot3d(reducedDim(sds), aspect = 'iso', col=brewer.pal(9,'Set1')[clDatta], alpha=.6)
plot3d.SlingshotDataSet(sds, add=TRUE, col=c("black"), lwd=4)
```

# Gene expression along pseudotime

## Hbegf

```{r}
labels <- c("Neur", "Sus", "rHBC")
names(labels) <- as.character(1:3)
plotSmoothers(sce, counts, gene="Hbegf") + 
  scale_color_viridis_d(labels=labels) + 
  ggtitle("Hbegf")

plot3d(reducedDim(sds), aspect = 'iso', col=colby(counts["Hbegf",], g=3), alpha=.6)
plot3d.SlingshotDataSet(sds, add=TRUE, col=c("black"), lwd=4)
rgl.snapshot('../plots/expressionTrajectory/3dplot_hbegf.png', fmt = 'png')
```

## Egfr targets

```{r}
egfrTargetDf <- read.csv("../data/genesTargets/egfr_targets_unfiltered.csv")
egfrTargets <- egfrTargetDf$target
egfrTargets <- intersect(egfrTargets, rownames(counts))
egfrTargetCounts <- counts[egfrTargets,]
egfrTargetScaledCounts <- t(scale(t(egfrTargetCounts)))


plot3d(reducedDim(sds), aspect = 'iso', col=brewer.pal(9,'Set1')[clDatta], alpha=.6)
plot3d.SlingshotDataSet(sds, add=TRUE, col=c("black"), lwd=4)

plot3d(reducedDim(sds), aspect = 'iso', col=colby(colMeans(egfrTargetScaledCounts), g=10), alpha=.6)
plot3d.SlingshotDataSet(sds, add=TRUE, col="black", lwd=4)
rgl.snapshot('../plots/expressionTrajectory/3dplot_egfrTargets.png', fmt = 'png')

# movie3d(
#   movie="3dOE_egfrTargets", 
#   spin3d( axis = c(0, 1, 0), rpm = 5),
#   duration = 20, 
#   dir = "~/",
#   type = "gif", 
#   clean = TRUE
# )


plot3d(reducedDim(sds), aspect = 'iso', col=colby(counts["Egfr",], g=3), alpha=.6)
plot3d.SlingshotDataSet(sds, add=TRUE, col=c("black"), lwd=4)
rgl.snapshot('../plots/expressionTrajectory/3dplot_egfr.png', fmt = 'png')
```

## Hopx

```{r}
plot3d(reducedDim(sds), aspect = 'iso', col=colby(counts["Hopx",], g=2), alpha=.6)
plot3d.SlingshotDataSet(sds, add=TRUE, col=c("black"), lwd=4)
```

## Areg

```{r}
plot3d(reducedDim(sds), aspect = 'iso', col=colby(counts["Areg",], g=3), alpha=.6)
plot3d.SlingshotDataSet(sds, add=TRUE, col=c("black"), lwd=4)
rgl.snapshot('../plots/expressionTrajectory/3dplot_areg.png', fmt = 'png')

sum(counts["Areg",] > 0)
```

## Hsp70 (Hspa1a)

```{r}
plot3d(reducedDim(sds), aspect = 'iso', col=colby(counts["Hspa1a",], g=3), alpha=.6)
plot3d.SlingshotDataSet(sds, add=TRUE, col=c("black"), lwd=4)
rgl.snapshot('../plots/expressionTrajectory/3dplot_hsp70.png', fmt = 'png')
```

## Ar

```{r}
plot3d(reducedDim(sds), aspect = 'iso', col=colby(counts["Ar",], g=2), alpha=.6)
plot3d.SlingshotDataSet(sds, add=TRUE, col=c("black"), lwd=4)
rgl.snapshot('../plots/expressionTrajectory/3dplot_ar.png', fmt = 'png')

sum(counts["Ar",] > 0)
```

## Trp53 / Trp63

```{r}
plot3d(reducedDim(sds), aspect = 'iso', col=colby(counts["Trp53",], g=3), alpha=.6)
plot3d.SlingshotDataSet(sds, add=TRUE, col=c("black"), lwd=4)
rgl.snapshot('../plots/expressionTrajectory/3dplot_trp53.png', fmt = 'png')


plot3d(reducedDim(sds), aspect = 'iso', col=colby(counts["Trp63",], g=3), alpha=.6)
plot3d.SlingshotDataSet(sds, add=TRUE, col=c("black"), lwd=4)
rgl.snapshot('../plots/expressionTrajectory/3dplot_trp63.png', fmt = 'png')

rafalib::mypar(mfrow=c(1,2))
plot(x=counts["Trp53",], y=counts["Trp63",],
     xlab="Trp53 expression", ylab="Trp63 expression")
smoothScatter(x=counts["Trp53",], y=counts["Trp63",],
     xlab="Trp53 expression", ylab="Trp63 expression")

```




# Heterogeneity in TF expression

```{r}
genesToPlot <- c("Hbegf", "Ets1", "Ets2", "Krt5", "Trp63", "Krt6a")
pList <- list()
for(gg in 1:length(genesToPlot)){
  pList[[gg]] <- plotSmoothers(sce, counts, gene=genesToPlot[gg], 
              plotLineages=FALSE, border=FALSE,
              pointCol = clDatta) + 
              ggtitle(genesToPlot[gg]) + ylim(c(0,5)) +
              theme(legend.position = "none")
}

p1 <- plotSmoothers(sce, counts, gene=genesToPlot[gg], 
              plotLineages=FALSE, border=FALSE,
              pointCol = clDatta) + ggtitle(genesToPlot[gg]) + ylim(c(0,5)) + 
    guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom")
leg <- cowplot::get_legend(p1)
pall <- cowplot::plot_grid(plotlist = pList)
pallLeg <- cowplot::plot_grid(pall, leg, nrow=2, rel_heights = c(0.9, 0.1))
pallLeg
```

# Figure 1

```{r}
labels <- c("Neur", "Sus", "rHBC")
names(labels) <- as.character(1:3)
traviz::plotSmoothers(sce, counts, gene="Fkbp15") + 
  scale_color_viridis_d(labels=labels) + 
  ggtitle("Fkbp15")
```

